name: Run tests
on:
  pull_request:
jobs:
  run-tests:
    if: github.event.pull_request.draft == false
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.2

    - name: Run Go test
      run: go test ./...

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        golangci_lint_flags: "--config .golangci.yaml --timeout 5m"
